### ISSUE TITLE
Raw Filter DB

### ISSUE THREAD

**Issue by MaulanaR** [zahir-core/grest#11]
The current condition is not yet possible to add DB Raw Query Filter 

Sample Code :
```
filterEmp.Filter = append(filterEmp.Filter, db.NewFilter("NOT EXISTS (SELECT 1 FROM payroll_details WHERE employee_id = e.id AND parent_id = '123')", "", nil))
```

Expected Result Query 
**SELECT * FROM e WHERE NOT EXISTS (SELECT 1 FROM payroll_details WHERE employee_id = e.id AND parent_id = '123'**)

Current Result Query
**SELECT * FROM e WHERE (NOT EXISTS (SELECT 1 FROM payroll_details WHERE employee_id = e.id AND parent_id = '123')) IS NULL**

**Comment by jeffry-luqman** [comment]
use this code
```go
filterEmp.Filter = append(filterEmp.Filter, db.NewFilter("NOT EXISTS (SELECT 1 FROM payroll_details WHERE employee_id = e.id AND parent_id = ?)", "", 123))
```
