### ISSUE TITLE
Cannot Filter hidden field

### ISSUE THREAD

**Issue by MaulanaR** [zahir-core/grest#2]
Step Reproduce Issue : 

1. Buat struct dengan notasi json"-"
![image](https://user-images.githubusercontent.com/16471471/165228956-80ef924d-ec73-410c-bd19-0eb435688b78.png)
2. Lakukan filter
![image](https://user-images.githubusercontent.com/16471471/165229012-f24df296-a966-4388-956d-cf971f467894.png)
3. Query yang terbentuk belum membawa filter yang dikirim
![image](https://user-images.githubusercontent.com/16471471/165229037-16edcbec-5572-4a00-93e7-9b4f51118e3b.png)

Goals : 
![image](https://user-images.githubusercontent.com/16471471/165229238-3108c7c9-eef3-4a65-a342-3b43ff8596b3.png)

**Comment by jeffry-luqman** [comment]
you can add `hide` on db tag to add filterable hidden field

```go
type Article struct {
	Model
	...
	IsHidden    NullBool     `json:"is_hidden"    db:"a.is_hidden,hide"`
	...
}
```
