### ISSUE TITLE
Fetch Semua Data

### ISSUE THREAD

**Issue by lismansihotang** [zahir-core/grest#32]
bagaimana cara nya mendapatkan semua data tanpa $page dan $per_page?

**Comment by MaulanaR** [comment]
kalau lewat url bisa ditambahkan  "$is_disable_pagination=true"
e.g ``` http://google.com?$is_disable_pagination=true```

atau kalau dalam kode, bisa seperti ini : 
```go
// find data
q := url.Values{}
q.Add(grest.QueryDisablePagination, "true")
data, err := app.Query().Find(tx, &DailyPurchase{}, q)`
```
